# sphinx-cookiecutter Documentation
---
title: "sphinx-cookiecutter"
author: "Jared Cook"
version: "0.1.0"
license: "AGPL-3.0-or-later"
copyright: "Copyright (c) 2025-2026, Jared Cook"
timezone: "America/Los_Angeles"
description: "sphinx cookiecutter template generation."
remote_theme: "just-the-docs/just-the-docs@v0.11.0"
ga_tracking: "G-C7PWLWSHB9"

repo_url: "https://github.com/jcook3701/sphinx-cookiecutter"
repo_blob: "https://github.com/jcook3701/sphinx-cookiecutter/blob/master"
github_io_url: "https://jcook3701.github.io/sphinx-cookiecutter"
repository: "jcook3701/sphinx-cookiecutter"

# Specifies the site's subpath for correct URL generation
baseurl: "/sphinx-cookiecutter"

collections:
  manual:
    output: true
    permalink: /:collection/:path

  resources:
    output: true
    permalink: /:collection/:path

just_the_docs:
  collections:
    manual:
      name: Manual
      nav_fold: true
      nav_exclude: false

    resources:
      name: "External Links"
      nav_fold: false
      nav_exclude: false

plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

# Author Remote User Accounts
# twitter_username: ""
github_username: "jcook3701"
linkedin_usercode: "jared-cook-b3585a114"
buymeacoffee_username: "jcook3701"

# carousel_images:
#  - /assets/images/
#  - /assets/images/
#  - /assets/images/

# Set a path/url to a logo that will be displayed instead of the title
# logo: /assets/images/icon128.png

# Enable or disable the site search
search_enabled: true

# For copy button on code
enable_copy_code_button: true

# By default, consuming the theme as a gem leaves mermaid disabled; it is opt-in
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"
  # Note: Put any additional configuration, such as setting the theme,
  #   in _includes/mermaid_config.js. See also docs/ui-components/code.
  # Note: To load mermaid from a local library, also use the `path` key
  #   to specify the location of the library; e.g. for (v10+):
  # path: "/assets/js/mermaid.esm.min.mjs" for (<v10):
  # path: "/assets/js/mermaid.min.js"
  # Note: copy both `mermaid.esm.min.mjs` (v10+) or `mermaid.min.js`
  #   (<v10) and the associated `.map` file from the specified version
  #   of `mermaid/dist` to `/assets/js/`.

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "sphinx-cookiecutter on GitHub":
    - "//github.com/jcook3701/sphinx-cookiecutter"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Enable or disable the side/mobile menu globally
# - Nav menu can also be selectively enabled or disabled
#     using page variables or the minimal layout
nav_enabled: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: >-
  Copyright (c) 2025-2026, Jared Cook. Distributed by an
  <a href="https://github.com/jcook3701/sphinx-cookiecutter/blob/master/LICENSE.md">
      AGPL-3.0-or-later license.
  </a>
  <a href=""></a>

## Footer last edited timestamp
# show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_timestamp: true
# uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
last_edit_time_format: >-
  %b %e %Y at %I:%M %p
## Footer "Edit this page on GitHub" link text
# show or hide edit this page link
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
# the github URL for your repo
gh_edit_repository: >-
  https://github.com/jcook3701/sphinx-cookiecutter
# the branch that your docs is served from
gh_edit_branch: "master"
# the source that your files originate from
gh_edit_source: docs
# "tree" or "edit" if you want the user to jump into the editor immediately
gh_edit_view_mode: "tree"

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

kramdown:
  auto_ids: true

include:
  - .well-known

# Exclude files/folders from Jekyll processing
exclude:
  - node_modules
  - .DS_Store
  - Gemfile
  - Gemfile.lock

# Optional SEO metadata
seo:
  title: "sphinx-cookiecutter Documentation"
  description: "Full code documentation for the sphinx-cookiecutter project"
