# black format
---
name: Cookiecutter Template Black Format Check

on: [push, pull_request]

jobs:
  black-format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Black
        run: |
          make install

      - name: Format check
        run: |
          make black-formatter-check
