# dependency-check
---
name: Cookiecutter Template Dependency Check

on: [push, pull_request]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deptry
        run: |
          make install

      - name: Run Dependency Check
        run: |
          make dependency-check
