# jinja2 lint
---
name: Cookiecutter template jinja2 lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  jinja2-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Jinja2 CLI
        run: |
          make install

      - name: Lint Jinja templates
        run: |
          make jinja2-lint-check
