# lint-check.yml for sphinx-cookiecutter
#
# Copyright (c) 2025, Jared Cook
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <www.gnu.org>.
#
---
name: Cookiecutter Template Lint Check

on: [push, pull_request]

jobs:
  jinja2-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Linting Tools
        run: |
          make install

      - name: Render Cookiecutter Template
        run: |
          make render-cookiecutter

      - name: Lint Jinja templates
        run: |
          make jinja2-lint-check
      - name: Run Ruff Lint Check
        run: |
          make ruff-lint-check
      - name: Run Toml Lint Check
        run: |
          make toml-lint-check
      - name: Run YAML Lint Check
        run: |
          make yaml-lint-check
