# lint check (jinja2, ruff, toml, & yaml)
---
name: Cookiecutter Template Jinja2 Lint

on: [push, pull_request]

jobs:
  jinja2-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Linting Tools
        run: |
          make install

      - name: Render Cookiecutter Template
        run: |
          make render-cookiecutter

      - name: Lint Jinja templates
        run: |
          make jinja2-lint-check
      - name: Run Ruff Lint Check
        run: |
          make ruff-lint-check
      - name: Run Toml Lint Check
        run: |
          make toml-lint-check
      - name: Run YAML Lint Check
        run: |
          make yaml-lint-check
