# tomllint
---
name: Cookiecutter Template Tomllint Lint

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  tomllint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Tomllint
        run: |
          make install

      - name: Lint YAML files
        run: |
          make toml-lint-check
